// every word in these arrays, should be unique to itself, "کابین", "ضد" like bug
export const listOfCategories = [
    { value: 1000, persian: "انواع روغن", persian2: "روغن", persian3: "روعن", persian4: "زوغن" },
    { value: 1001, persian: "روغن موتور", persian2: "روعن موتور", persian3: "موتور" },
    { value: 1002, persian: "روغن گیربکس", persian2: "گیربکس", persian3: "روغن دنده", persian4: "دنده", persian5: "گیریبکس" },
    { value: 1003, persian: "روغن ترمز", persian2: "ترمز", persian3: "نرمز", persian4: "ترمر", persian5: "تزمز", persian6: "تزمر" },
    { value: 1004, persian: "روغن هیدرولیک", persian2: "هیدرولیک", persian3: "فرمان", persian4: "روغن فرمان" },
    { value: 1005, persian: "مکمل سوخت", persian2: "مکمل", persian3: "سوخت", persian4: "اکتان", persian5: "بنزین", persian6: "بوستر" },
    { value: 1006, persian: "ضد یخ", persian2: "ضدیخ", persian3: "ضد بخ", persian4: "یخ", persian5: "ضد" },
    { value: 1006, persian: "ضد جوش", persian2: "ضدجوش", persian3: "جوش", persian4: "حوش" },
    {
        value: 1007,
        persian: "آب رادیاتور",
        persian2: "اب رادیاتور",
        persian3: "آب رادباتور",
        persian4: "آب",
        persian5: "رادیاتور",
        persian6: "اب",
    },
    { value: 1008, persian: "گریس", persian2: "روان کننده", persian3: "کریس", persian4: "روان", persian4: "گریس کننده" },
    { value: 2000, persian: "انواع فیلتر", persian2: "فیلنر", persian3: "فبلتر", persian4: "فیلتر" },
    {
        value: 2001,
        persian: "فیلتر هوای موتور",
        persian2: "فیلتر هوا موتور",
        persian3: "فیلتر هوا",
        persian4: "فیلتر هوای",
        persian5: "هوا",
    },
    { value: 2002, persian: "فیلتر سوخت", persian2: "فیلترسوخت", persian3: "فیلنر سوخت", persian4: "فیلتر بنزین" },
    { value: 2003, persian: "فیلتر روغن", persian2: "فیلنر روغن", persian3: "فبلتر روغن" },
    {
        value: 2004,
        persian: "فیلتر هوای کابین",
        persian2: "فیلتر کابین",
        persian3: "فیلنر کابین",
        persian4: "کابین",
        persian5: "فیلتر اتاق",
        persian6: "اتاق",
    },
];

export const listOfBrands = [
    { value: "کاسپین", persian: "کاسپین", persian2: "کاسبین", persian3: "کلسپین", persian4: "کاسپ" },
    { value: "ارو", persian: "ارو", persian2: "آرو", persian3: "ازو", persian4: "آزو" },
    { value: "نفت پارس", persian: "نفت پارس", persian2: "پایا", persian3: "نفت", persian4: "پارس" },
    { value: "فلومکس", persian: "فلومکس", persian2: "فلو مکس", persian3: "قلومکس", persian4: "فلو" },
    { value: "لیکومولی", persian: "لیکومولی", persian2: "لیکو مولی", persian3: "مولی", persian4: "لیکو" },
    { value: "اسپیدی", persian: "اسپیدی", persian2: "اسبیدی", persian3: "اسپی" },
    { value: "بهران", persian: "بهران", persian2: "تهران", persian3: "بهرا" },
    { value: "ایرانول", persian: "ایرانول", persian2: "ایراتول", persian3: "ابرانول" },
    { value: "کاسترول", persian: "کاسترول", persian2: "کلسترول", persian3: "کاستر", persian4: "کاسترو" },
    { value: "توتال", persian: "توتال", persian2: "تونال", persian3: "نوتال", persian4: "توت" },
    { value: "الف", persian: "الف", persian2: "علف" },
    { value: "بوش", persian: "بوش", persian2: "یوش", persian3: "بوس" },
    { value: "مگلوب", persian: "مگلوب", persian2: "مغلوب", persian3: "مکلوب", persian4: "مقلوب" },
];

export const listOfCategoriesToSelect = [
    { value: 1000, persian: "انواع روغن", english: "Oils" },
    { value: 1001, persian: "روغن موتور", english: "Engine Oil" },
    { value: 1002, persian: "روغن گیربکس", english: "Gear Oil" },
    { value: 1003, persian: "روغن ترمز", english: "Brake Fluid" },
    { value: 1004, persian: "روغن هیدرولیک", english: "Hydraulic Oil" },
    { value: 1005, persian: "مکمل سوخت", english: "Octane Booster" },
    { value: 1006, persian: "ضد یخ", english: "Antifreeze" },
    { value: 1007, persian: "آب رادیاتور", english: "Radiator-System Water" },
    { value: 2000, persian: "انواع فیلتر", english: "Filters" },
    { value: 2001, persian: "فیلتر هوای موتور", english: "Engine-Air Filter" },
    { value: 2002, persian: "فیلتر سوخت", english: "Fuil-Sys Filter" },
    { value: 2003, persian: "فیلتر روغن", english: "Oil Filter" },
    { value: 2004, persian: "فیلتر هوای کابین", english: "Cabin-Air Filter" },
];

export const listOfBrandsToSelect = [
    { value: "کاسپین", persian: " کاسپین", english: "Caspian" },
    { value: "فلومکس", persian: " فلومکس", english: "Flowmax" },
    { value: "ارو", persian: " ارو", english: "Arrow" },
    { value: "نفت پارس", persian: " نفت پارس", english: "Pars-Oil" },
];
